# Generated by Django 4.2.7 on 2023-11-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая стоимость')),
                ('century', models.IntegerField(verbose_name='Век создания')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ширина')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина')),
                ('temperature_control', models.BooleanField(verbose_name='Необходимость контроля температуры')),
                ('humidity_control', models.BooleanField(verbose_name='Необходимость контроля влажности')),
                ('protection', models.BooleanField(verbose_name='Защищённость от людей')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.exhibit', verbose_name='Коллекция')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.hall', verbose_name='Зал')),
            ],
        ),
    ]
