# Generated by Django 4.2.7 on 2023-11-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name': 'Экспонат', 'verbose_name_plural': 'Экспонаты'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Выставочный зал', 'verbose_name_plural': 'Выставочные залы'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.collection', verbose_name='Коллекция'),
        ),
    ]
